Chapter 03

# Python自定义函数计算矩阵乘法，行向量线性组合视角
《线性代数》 | 鸢尾花书：数学不难

这段代码从数学角度重新阐释了**矩阵乘法的行向量线性组合视角**，本质上与传统的矩阵乘法是一致的，但提供了另一种对“线性运算”的理解方式。代码分为两个主要部分：一个用于实现**行向量的线性组合**，另一个用于基于该组合思想完成矩阵乘法 $AB$。

---

### 一、矩阵乘法的行向量解释

设矩阵 $A \in \mathbb{R}^{m \times p}$，$B \in \mathbb{R}^{p \times n}$，矩阵乘积 $C = AB \in \mathbb{R}^{m \times n}$ 的第 $i$ 行可以表示为：

$$
C[i, :] = \sum_{k=1}^p A[i, k] \cdot B[k, :]
$$

也就是说，**$C$ 的第 $i$ 行**是由 $B$ 的行向量 $\{B[1,:], B[2,:], \dots, B[p,:]\}$ 加权组合得到的，其中权重是 $A$ 的第 $i$ 行。

换句话说，把 $A$ 的第 $i$ 行视为一组线性组合系数，作用在 $B$ 的行上，得到 $C$ 的第 $i$ 行。

---

### 二、函数 `row_LC` 的数学含义

函数 `row_LC(B, coefficients)` 所做的事是：

> 给定一个矩阵 $B \in \mathbb{R}^{p \times n}$，和一个系数向量 $\mathbf{a} \in \mathbb{R}^{p}$，计算线性组合：
$$
\mathbf{v} = \sum_{k=1}^p a_k \cdot \mathbf{b}_k
$$
其中 $\mathbf{b}_k = B[k, :]$ 是 $B$ 的第 $k$ 行。

这个过程本质上是将 $B$ 看作由 $p$ 个 $n$ 维行向量组成，对这些行向量进行线性加权。

---

### 三、函数 `matrix_multiplication_row_LC` 的数学含义

该函数的目的是用**行向量线性组合的方式计算矩阵乘积**，即：

设 $A \in \mathbb{R}^{m \times p}$，$B \in \mathbb{R}^{p \times n}$，则对每个 $i = 1, \dots, m$：

- 取 $A$ 的第 $i$ 行 $\mathbf{a}_i = A[i, :]$
- 结果 $C$ 的第 $i$ 行是：
$$
C[i, :] = \sum_{k=1}^p a_{ik} \cdot B[k, :]
$$

从而得到整个矩阵乘积：
$$
C = AB \in \mathbb{R}^{m \times n}
$$

这实际上是对矩阵乘法
$$
C_{ij} = \sum_{k=1}^p A_{ik} B_{kj}
$$
的**按行视角重写**。

---

### 四、具体矩阵示例

我们定义：

$$
A = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix} \in \mathbb{R}^{2 \times 3}, \quad
B = A^T = \begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix} \in \mathbb{R}^{3 \times 2}
$$

---

### 五、计算 $AB$（行组合）

通过 `matrix_multiplication_row_LC(A, B)` 得到：
$$
AB = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
=
\begin{bmatrix}
14 & 32 \\
32 & 77
\end{bmatrix}
$$

计算细节：

- 第1行组合权重为 $[1, 2, 3]$：
  $$
  1 \cdot B[0,:] + 2 \cdot B[1,:] + 3 \cdot B[2,:] =
  1 \cdot [1, 4] + 2 \cdot [2, 5] + 3 \cdot [3, 6] =
  [14, 32]
  $$

- 第2行组合权重为 $[4, 5, 6]$：
  $$
  4 \cdot [1, 4] + 5 \cdot [2, 5] + 6 \cdot [3, 6] =
  [32, 77]
  $$

这验证了矩阵乘法 $AB$ 可以通过 **行向量组合 $B$ 的行** 得到。

---

### 六、计算 $BA$（行组合）

我们再反过来看 `matrix_multiplication_row_LC(B, A)`，即：

$$
BA = \begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
=
\begin{bmatrix}
17 & 22 & 27 \\
22 & 29 & 36 \\
27 & 36 & 45
\end{bmatrix}
$$

这里每一行结果是将 $A$ 的行向量 $[1, 2, 3], [4, 5, 6]$ 作为**加权对象**，使用 $B$ 的行作为权重。

例如，第1行组合是：
$$
1 \cdot [1, 2, 3] + 4 \cdot [4, 5, 6] = [17, 22, 27]
$$

---

### 七、总结

整个过程本质上是通过**行向量线性组合**来理解矩阵乘法：

- 每一行结果是组合 $B$ 的行向量得到的；
- 线性组合系数是来自矩阵 $A$ 的行；
- 和传统矩阵乘法结果一致，但提供了**更强的直观性与结构感知**。

公式表达如下：

$$
(AB)[i, :] = \sum_{k=1}^p A[i, k] \cdot B[k, :] \quad \forall i = 1, \dots, m
$$

这种方式有助于从**行空间**理解线性变换，尤其在深度学习中（如前向传播中的仿射变换）具有良好解释力。

## 初始化

In [ ]:
import numpy as np

## 定义行向量线性组合函数

In [ ]:
def row_LC(B, coefficients):

    p, n = B.shape
    row_LC_result = np.zeros(n)  # 初始化组合结果
    
    for k in range(p):
        row_LC_result += coefficients[k] * B[k,:]  
        # 每行乘系数并相加
    return row_LC_result

## 定义矩阵乘法函数（行线性组合法）

In [ ]:
def matrix_multiplication_row_LC(A, B):
    # 获取矩阵 A 和 B 的形状
    m, p_A = A.shape
    p_B, n = B.shape

    # 检测矩阵形状是否符合矩阵乘法规则
    if p_A != p_B:
        raise ValueError('Dimensions do not match')

    # 初始化结果矩阵 C，形状 (m, n)，初始值设为 0
    C = np.zeros((m, n))

    for i in range(m):
        coeffs = A[i, :]             
        # 取出 A 的第 i 列，作为线性组合的系数
        C[i,:] = row_LC(B, coeffs)  
        # 计算 B 行向量的线性组合
    
    return C

## 矩阵乘法

In [11]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
B = A.T
B

array([[1, 4],
       [2, 5],
       [3, 6]])

## 矩阵乘法

In [18]:
matrix_multiplication_row_LC(A, B)

array([[14., 32.],
       [32., 77.]])

In [ ]:
A @ B

In [20]:
matrix_multiplication_row_LC(B, A)

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]])

In [ ]:
B @ A

作者	**生姜DrGinger**  
脚本	**生姜DrGinger**  
视频	**崔崔CuiCui**  
开源资源	[**GitHub**](https://github.com/Visualize-ML)  
平台	[**油管**](https://www.youtube.com/@DrGinger_Jiang)		
		[**iris小课堂**](https://space.bilibili.com/3546865719052873)		
		[**生姜DrGinger**](https://space.bilibili.com/513194466)  